/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_lang_StringCoding */

#ifndef _Included_java_lang_StringCoding
#define _Included_java_lang_StringCoding
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     java_lang_StringCoding
 * Method:    err
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_java_lang_StringCoding_err
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
