/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_io_FileDescriptor */

#ifndef _Included_java_io_FileDescriptor
#define _Included_java_io_FileDescriptor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     java_io_FileDescriptor
 * Method:    sync
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_java_io_FileDescriptor_sync
  (JNIEnv *, jobject);

/*
 * Class:     java_io_FileDescriptor
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_java_io_FileDescriptor_initIDs
  (JNIEnv *, jclass);

/*
 * Class:     java_io_FileDescriptor
 * Method:    getHandle
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_java_io_FileDescriptor_getHandle
  (JNIEnv *, jclass, jint);

/*
 * Class:     java_io_FileDescriptor
 * Method:    getAppend
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_java_io_FileDescriptor_getAppend
  (JNIEnv *, jclass, jint);

/*
 * Class:     java_io_FileDescriptor
 * Method:    close0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_java_io_FileDescriptor_close0
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
