/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_lang_StackStreamFactory */

#ifndef _Included_java_lang_StackStreamFactory
#define _Included_java_lang_StackStreamFactory
#ifdef __cplusplus
extern "C" {
#endif
#undef java_lang_StackStreamFactory_SMALL_BATCH
#define java_lang_StackStreamFactory_SMALL_BATCH 8L
#undef java_lang_StackStreamFactory_BATCH_SIZE
#define java_lang_StackStreamFactory_BATCH_SIZE 32L
#undef java_lang_StackStreamFactory_LARGE_BATCH_SIZE
#define java_lang_StackStreamFactory_LARGE_BATCH_SIZE 256L
#undef java_lang_StackStreamFactory_MIN_BATCH_SIZE
#define java_lang_StackStreamFactory_MIN_BATCH_SIZE 8L
#undef java_lang_StackStreamFactory_DEFAULT_MODE
#define java_lang_StackStreamFactory_DEFAULT_MODE 0L
#undef java_lang_StackStreamFactory_FILL_CLASS_REFS_ONLY
#define java_lang_StackStreamFactory_FILL_CLASS_REFS_ONLY 2L
#undef java_lang_StackStreamFactory_GET_CALLER_CLASS
#define java_lang_StackStreamFactory_GET_CALLER_CLASS 4L
#undef java_lang_StackStreamFactory_SHOW_HIDDEN_FRAMES
#define java_lang_StackStreamFactory_SHOW_HIDDEN_FRAMES 32L
#undef java_lang_StackStreamFactory_FILL_LIVE_STACK_FRAMES
#define java_lang_StackStreamFactory_FILL_LIVE_STACK_FRAMES 256L
/*
 * Class:     java_lang_StackStreamFactory
 * Method:    checkStackWalkModes
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_java_lang_StackStreamFactory_checkStackWalkModes
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
