/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_lang_StackStreamFactory_AbstractStackWalker */

#ifndef _Included_java_lang_StackStreamFactory_AbstractStackWalker
#define _Included_java_lang_StackStreamFactory_AbstractStackWalker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     java_lang_StackStreamFactory_AbstractStackWalker
 * Method:    callStackWalk
 * Signature: (JIII[Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_java_lang_StackStreamFactory_00024AbstractStackWalker_callStackWalk
  (JNIEnv *, jobject, jlong, jint, jint, jint, jobjectArray);

/*
 * Class:     java_lang_StackStreamFactory_AbstractStackWalker
 * Method:    fetchStackFrames
 * Signature: (JJII[Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_java_lang_StackStreamFactory_00024AbstractStackWalker_fetchStackFrames
  (JNIEnv *, jobject, jlong, jlong, jint, jint, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
