/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_lang_SecurityManager */

#ifndef _Included_java_lang_SecurityManager
#define _Included_java_lang_SecurityManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     java_lang_SecurityManager
 * Method:    getClassContext
 * Signature: ()[Ljava/lang/Class;
 */
JNIEXPORT jobjectArray JNICALL Java_java_lang_SecurityManager_getClassContext
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
