/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_util_zip_Inflater */

#ifndef _Included_java_util_zip_Inflater
#define _Included_java_util_zip_Inflater
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     java_util_zip_Inflater
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_java_util_zip_Inflater_initIDs
  (JNIEnv *, jclass);

/*
 * Class:     java_util_zip_Inflater
 * Method:    init
 * Signature: (Z)J
 */
JNIEXPORT jlong JNICALL Java_java_util_zip_Inflater_init
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     java_util_zip_Inflater
 * Method:    setDictionary
 * Signature: (J[BII)V
 */
JNIEXPORT void JNICALL Java_java_util_zip_Inflater_setDictionary
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint);

/*
 * Class:     java_util_zip_Inflater
 * Method:    setDictionaryBuffer
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_java_util_zip_Inflater_setDictionaryBuffer
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     java_util_zip_Inflater
 * Method:    inflateBytesBytes
 * Signature: (J[BII[BII)J
 */
JNIEXPORT jlong JNICALL Java_java_util_zip_Inflater_inflateBytesBytes
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jint, jbyteArray, jint, jint);

/*
 * Class:     java_util_zip_Inflater
 * Method:    inflateBytesBuffer
 * Signature: (J[BIIJI)J
 */
JNIEXPORT jlong JNICALL Java_java_util_zip_Inflater_inflateBytesBuffer
  (JNIEnv *, jobject, jlong, jbyteArray, jint, jint, jlong, jint);

/*
 * Class:     java_util_zip_Inflater
 * Method:    inflateBufferBytes
 * Signature: (JJI[BII)J
 */
JNIEXPORT jlong JNICALL Java_java_util_zip_Inflater_inflateBufferBytes
  (JNIEnv *, jobject, jlong, jlong, jint, jbyteArray, jint, jint);

/*
 * Class:     java_util_zip_Inflater
 * Method:    inflateBufferBuffer
 * Signature: (JJIJI)J
 */
JNIEXPORT jlong JNICALL Java_java_util_zip_Inflater_inflateBufferBuffer
  (JNIEnv *, jobject, jlong, jlong, jint, jlong, jint);

/*
 * Class:     java_util_zip_Inflater
 * Method:    getAdler
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_java_util_zip_Inflater_getAdler
  (JNIEnv *, jclass, jlong);

/*
 * Class:     java_util_zip_Inflater
 * Method:    reset
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_java_util_zip_Inflater_reset
  (JNIEnv *, jclass, jlong);

/*
 * Class:     java_util_zip_Inflater
 * Method:    end
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_java_util_zip_Inflater_end
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
