/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_lang_Module */

#ifndef _Included_java_lang_Module
#define _Included_java_lang_Module
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     java_lang_Module
 * Method:    defineModule0
 * Signature: (Ljava/lang/Module;ZLjava/lang/String;Ljava/lang/String;[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_java_lang_Module_defineModule0
  (JNIEnv *, jclass, jobject, jboolean, jstring, jstring, jobjectArray);

/*
 * Class:     java_lang_Module
 * Method:    addReads0
 * Signature: (Ljava/lang/Module;Ljava/lang/Module;)V
 */
JNIEXPORT void JNICALL Java_java_lang_Module_addReads0
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     java_lang_Module
 * Method:    addExports0
 * Signature: (Ljava/lang/Module;Ljava/lang/String;Ljava/lang/Module;)V
 */
JNIEXPORT void JNICALL Java_java_lang_Module_addExports0
  (JNIEnv *, jclass, jobject, jstring, jobject);

/*
 * Class:     java_lang_Module
 * Method:    addExportsToAll0
 * Signature: (Ljava/lang/Module;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_java_lang_Module_addExportsToAll0
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     java_lang_Module
 * Method:    addExportsToAllUnnamed0
 * Signature: (Ljava/lang/Module;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_java_lang_Module_addExportsToAllUnnamed0
  (JNIEnv *, jclass, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
