/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_net_SocketCleanable */

#ifndef _Included_java_net_SocketCleanable
#define _Included_java_net_SocketCleanable
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     java_net_SocketCleanable
 * Method:    cleanupClose0
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_java_net_SocketCleanable_cleanupClose0
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
