/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jdk_internal_reflect_NativeConstructorAccessorImpl */

#ifndef _Included_jdk_internal_reflect_NativeConstructorAccessorImpl
#define _Included_jdk_internal_reflect_NativeConstructorAccessorImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jdk_internal_reflect_NativeConstructorAccessorImpl
 * Method:    newInstance0
 * Signature: (Ljava/lang/reflect/Constructor;[Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_jdk_internal_reflect_NativeConstructorAccessorImpl_newInstance0
  (JNIEnv *, jclass, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
