/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jdk_internal_misc_VM */

#ifndef _Included_jdk_internal_misc_VM
#define _Included_jdk_internal_misc_VM
#ifdef __cplusplus
extern "C" {
#endif
#undef jdk_internal_misc_VM_JAVA_LANG_SYSTEM_INITED
#define jdk_internal_misc_VM_JAVA_LANG_SYSTEM_INITED 1L
#undef jdk_internal_misc_VM_MODULE_SYSTEM_INITED
#define jdk_internal_misc_VM_MODULE_SYSTEM_INITED 2L
#undef jdk_internal_misc_VM_SYSTEM_LOADER_INITIALIZING
#define jdk_internal_misc_VM_SYSTEM_LOADER_INITIALIZING 3L
#undef jdk_internal_misc_VM_SYSTEM_BOOTED
#define jdk_internal_misc_VM_SYSTEM_BOOTED 4L
#undef jdk_internal_misc_VM_SYSTEM_SHUTDOWN
#define jdk_internal_misc_VM_SYSTEM_SHUTDOWN 5L
#undef jdk_internal_misc_VM_JVMTI_THREAD_STATE_ALIVE
#define jdk_internal_misc_VM_JVMTI_THREAD_STATE_ALIVE 1L
#undef jdk_internal_misc_VM_JVMTI_THREAD_STATE_TERMINATED
#define jdk_internal_misc_VM_JVMTI_THREAD_STATE_TERMINATED 2L
#undef jdk_internal_misc_VM_JVMTI_THREAD_STATE_RUNNABLE
#define jdk_internal_misc_VM_JVMTI_THREAD_STATE_RUNNABLE 4L
#undef jdk_internal_misc_VM_JVMTI_THREAD_STATE_BLOCKED_ON_MONITOR_ENTER
#define jdk_internal_misc_VM_JVMTI_THREAD_STATE_BLOCKED_ON_MONITOR_ENTER 1024L
#undef jdk_internal_misc_VM_JVMTI_THREAD_STATE_WAITING_INDEFINITELY
#define jdk_internal_misc_VM_JVMTI_THREAD_STATE_WAITING_INDEFINITELY 16L
#undef jdk_internal_misc_VM_JVMTI_THREAD_STATE_WAITING_WITH_TIMEOUT
#define jdk_internal_misc_VM_JVMTI_THREAD_STATE_WAITING_WITH_TIMEOUT 32L
/*
 * Class:     jdk_internal_misc_VM
 * Method:    latestUserDefinedLoader0
 * Signature: ()Ljava/lang/ClassLoader;
 */
JNIEXPORT jobject JNICALL Java_jdk_internal_misc_VM_latestUserDefinedLoader0
  (JNIEnv *, jclass);

/*
 * Class:     jdk_internal_misc_VM
 * Method:    getuid
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jdk_internal_misc_VM_getuid
  (JNIEnv *, jclass);

/*
 * Class:     jdk_internal_misc_VM
 * Method:    geteuid
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jdk_internal_misc_VM_geteuid
  (JNIEnv *, jclass);

/*
 * Class:     jdk_internal_misc_VM
 * Method:    getgid
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jdk_internal_misc_VM_getgid
  (JNIEnv *, jclass);

/*
 * Class:     jdk_internal_misc_VM
 * Method:    getegid
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jdk_internal_misc_VM_getegid
  (JNIEnv *, jclass);

/*
 * Class:     jdk_internal_misc_VM
 * Method:    getNanoTimeAdjustment
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jdk_internal_misc_VM_getNanoTimeAdjustment
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jdk_internal_misc_VM
 * Method:    getRuntimeArguments
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_jdk_internal_misc_VM_getRuntimeArguments
  (JNIEnv *, jclass);

/*
 * Class:     jdk_internal_misc_VM
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jdk_internal_misc_VM_initialize
  (JNIEnv *, jclass);

/*
 * Class:     jdk_internal_misc_VM
 * Method:    initializeFromArchive
 * Signature: (Ljava/lang/Class;)V
 */
JNIEXPORT void JNICALL Java_jdk_internal_misc_VM_initializeFromArchive
  (JNIEnv *, jclass, jclass);

#ifdef __cplusplus
}
#endif
#endif
