/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jdk_internal_vm_VMSupport */

#ifndef _Included_jdk_internal_vm_VMSupport
#define _Included_jdk_internal_vm_VMSupport
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jdk_internal_vm_VMSupport
 * Method:    initAgentProperties
 * Signature: (Ljava/util/Properties;)Ljava/util/Properties;
 */
JNIEXPORT jobject JNICALL Java_jdk_internal_vm_VMSupport_initAgentProperties
  (JNIEnv *, jclass, jobject);

/*
 * Class:     jdk_internal_vm_VMSupport
 * Method:    getVMTemporaryDirectory
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jdk_internal_vm_VMSupport_getVMTemporaryDirectory
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
