/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jdk_internal_loader_BootLoader */

#ifndef _Included_jdk_internal_loader_BootLoader
#define _Included_jdk_internal_loader_BootLoader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jdk_internal_loader_BootLoader
 * Method:    getSystemPackageNames
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_jdk_internal_loader_BootLoader_getSystemPackageNames
  (JNIEnv *, jclass);

/*
 * Class:     jdk_internal_loader_BootLoader
 * Method:    getSystemPackageLocation
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jdk_internal_loader_BootLoader_getSystemPackageLocation
  (JNIEnv *, jclass, jstring);

/*
 * Class:     jdk_internal_loader_BootLoader
 * Method:    setBootLoaderUnnamedModule0
 * Signature: (Ljava/lang/Module;)V
 */
JNIEXPORT void JNICALL Java_jdk_internal_loader_BootLoader_setBootLoaderUnnamedModule0
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
