/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jdk_internal_reflect_NativeMethodAccessorImpl */

#ifndef _Included_jdk_internal_reflect_NativeMethodAccessorImpl
#define _Included_jdk_internal_reflect_NativeMethodAccessorImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jdk_internal_reflect_NativeMethodAccessorImpl
 * Method:    invoke0
 * Signature: (Ljava/lang/reflect/Method;Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_jdk_internal_reflect_NativeMethodAccessorImpl_invoke0
  (JNIEnv *, jclass, jobject, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
