/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jdk_internal_misc_Signal */

#ifndef _Included_jdk_internal_misc_Signal
#define _Included_jdk_internal_misc_Signal
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jdk_internal_misc_Signal
 * Method:    findSignal0
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_jdk_internal_misc_Signal_findSignal0
  (JNIEnv *, jclass, jstring);

/*
 * Class:     jdk_internal_misc_Signal
 * Method:    handle0
 * Signature: (IJ)J
 */
JNIEXPORT jlong JNICALL Java_jdk_internal_misc_Signal_handle0
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     jdk_internal_misc_Signal
 * Method:    raise0
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jdk_internal_misc_Signal_raise0
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
