/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_nio_ch_SocketChannelImpl */

#ifndef _Included_sun_nio_ch_SocketChannelImpl
#define _Included_sun_nio_ch_SocketChannelImpl
#ifdef __cplusplus
extern "C" {
#endif
#undef sun_nio_ch_SocketChannelImpl_ST_UNCONNECTED
#define sun_nio_ch_SocketChannelImpl_ST_UNCONNECTED 0L
#undef sun_nio_ch_SocketChannelImpl_ST_CONNECTIONPENDING
#define sun_nio_ch_SocketChannelImpl_ST_CONNECTIONPENDING 1L
#undef sun_nio_ch_SocketChannelImpl_ST_CONNECTED
#define sun_nio_ch_SocketChannelImpl_ST_CONNECTED 2L
#undef sun_nio_ch_SocketChannelImpl_ST_CLOSING
#define sun_nio_ch_SocketChannelImpl_ST_CLOSING 3L
#undef sun_nio_ch_SocketChannelImpl_ST_KILLPENDING
#define sun_nio_ch_SocketChannelImpl_ST_KILLPENDING 4L
#undef sun_nio_ch_SocketChannelImpl_ST_KILLED
#define sun_nio_ch_SocketChannelImpl_ST_KILLED 5L
/*
 * Class:     sun_nio_ch_SocketChannelImpl
 * Method:    checkConnect
 * Signature: (Ljava/io/FileDescriptor;Z)I
 */
JNIEXPORT jint JNICALL Java_sun_nio_ch_SocketChannelImpl_checkConnect
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     sun_nio_ch_SocketChannelImpl
 * Method:    sendOutOfBandData
 * Signature: (Ljava/io/FileDescriptor;B)I
 */
JNIEXPORT jint JNICALL Java_sun_nio_ch_SocketChannelImpl_sendOutOfBandData
  (JNIEnv *, jclass, jobject, jbyte);

#ifdef __cplusplus
}
#endif
#endif
