/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sun_nio_ch_PollSelectorImpl */

#ifndef _Included_sun_nio_ch_PollSelectorImpl
#define _Included_sun_nio_ch_PollSelectorImpl
#ifdef __cplusplus
extern "C" {
#endif
#undef sun_nio_ch_PollSelectorImpl_INITIAL_CAPACITY
#define sun_nio_ch_PollSelectorImpl_INITIAL_CAPACITY 16L
#undef sun_nio_ch_PollSelectorImpl_SIZE_POLLFD
#define sun_nio_ch_PollSelectorImpl_SIZE_POLLFD 8L
#undef sun_nio_ch_PollSelectorImpl_FD_OFFSET
#define sun_nio_ch_PollSelectorImpl_FD_OFFSET 0L
#undef sun_nio_ch_PollSelectorImpl_EVENT_OFFSET
#define sun_nio_ch_PollSelectorImpl_EVENT_OFFSET 4L
#undef sun_nio_ch_PollSelectorImpl_REVENT_OFFSET
#define sun_nio_ch_PollSelectorImpl_REVENT_OFFSET 6L
/*
 * Class:     sun_nio_ch_PollSelectorImpl
 * Method:    poll
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_sun_nio_ch_PollSelectorImpl_poll
  (JNIEnv *, jclass, jlong, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
