@setlocal

REM
REM This script deletes UNIX symbolic links and recreates them as windows symbolic links.
REM Creating symbolic links requires special permissions therefore you have to run
REM this script as administrator (right click in Explorer and select "Run as administrator")
REM

REM change to parent directory of the running script
cd %~dp0

del "hotspot_sys_headers_and_outputdir_src\linux_ppc_64\sys_headers\usr\include\asm"
mklink /D "hotspot_sys_headers_and_outputdir_src\linux_ppc_64\sys_headers\usr\include\asm" "asm-powerpc"
del "hotspot_sys_headers_and_outputdir_src\linux_s390_64\sys_headers\usr\include\asm"
mklink /D "hotspot_sys_headers_and_outputdir_src\linux_s390_64\sys_headers\usr\include\asm" "asm-s390"
del "hotspot_sys_headers_and_outputdir_src\linux_s390_64\sys_headers\usr\include\c++\4.3\s390x-suse-linux\32"
mklink /D "hotspot_sys_headers_and_outputdir_src\linux_s390_64\sys_headers\usr\include\c++\4.3\s390x-suse-linux\32" "."
del "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\bits"
mklink /D "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\bits" "x86_64-linux-gnu\bits"
del "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\asm"
mklink /D "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\asm" "x86_64-linux-gnu\asm"
del "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\gnu"
mklink /D "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\gnu" "x86_64-linux-gnu\gnu"
del "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\x86_64-linux-gnu\c++\5.4.0"
mklink /D "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\x86_64-linux-gnu\c++\5.4.0" "5"
del "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\c++\5.4.0"
mklink /D "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\c++\5.4.0" "5"
del "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\cdefs.h"
mklink    "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\cdefs.h" "..\x86_64-linux-gnu\sys\cdefs.h"
del "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\time.h"
mklink    "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\time.h" "..\x86_64-linux-gnu\sys\time.h"
del "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\ioctl.h"
mklink    "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\ioctl.h" "..\x86_64-linux-gnu\sys\ioctl.h"
del "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\stat.h"
mklink    "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\stat.h" "..\x86_64-linux-gnu\sys\stat.h"
del "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\poll.h"
mklink    "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\poll.h" "..\x86_64-linux-gnu\sys\poll.h"
del "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\uio.h"
mklink    "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\uio.h" "..\x86_64-linux-gnu\sys\uio.h"
del "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\utsname.h"
mklink    "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\utsname.h" "..\x86_64-linux-gnu\sys\utsname.h"
del "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\param.h"
mklink    "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\param.h" "..\x86_64-linux-gnu\sys\param.h"
del "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\socket.h"
mklink    "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\socket.h" "..\x86_64-linux-gnu\sys\socket.h"
del "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\sysinfo.h"
mklink    "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\sysinfo.h" "..\x86_64-linux-gnu\sys\sysinfo.h"
del "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\resource.h"
mklink    "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\resource.h" "..\x86_64-linux-gnu\sys\resource.h"
del "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\shm.h"
mklink    "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\shm.h" "..\x86_64-linux-gnu\sys\shm.h"
del "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\ttydefaults.h"
mklink    "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\ttydefaults.h" "..\x86_64-linux-gnu\sys\ttydefaults.h"
del "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\times.h"
mklink    "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\times.h" "..\x86_64-linux-gnu\sys\times.h"
del "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\select.h"
mklink    "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\select.h" "..\x86_64-linux-gnu\sys\select.h"
del "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\syscall.h"
mklink    "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\syscall.h" "..\x86_64-linux-gnu\sys\syscall.h"
del "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\ucontext.h"
mklink    "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\ucontext.h" "..\x86_64-linux-gnu\sys\ucontext.h"
del "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\ipc.h"
mklink    "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\ipc.h" "..\x86_64-linux-gnu\sys\ipc.h"
del "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\types.h"
mklink    "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\types.h" "..\x86_64-linux-gnu\sys\types.h"
del "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\wait.h"
mklink    "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\wait.h" "..\x86_64-linux-gnu\sys\wait.h"
del "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\mman.h"
mklink    "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\mman.h" "..\x86_64-linux-gnu\sys\mman.h"
del "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\sysmacros.h"
mklink    "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\sysmacros.h" "..\x86_64-linux-gnu\sys\sysmacros.h"
pause
