@setlocal

REM
REM This script deletes UNIX symbolic links and recreates them as windows symbolic links.
REM Creating symbolic links requires special permissions therefore you have to run
REM this script as administrator (right click in Explorer and select "Run as administrator")
REM

REM change to parent directory of the running script
cd %~dp0

del "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\Library\Frameworks\NyxAudioAnalysis.framework"
mklink    "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\Library\Frameworks\NyxAudioAnalysis.framework" "..\..\System\Library\PrivateFrameworks\NyxAudioAnalysis.framework"
del "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\WebKit.framework\Frameworks"
mklink    "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\WebKit.framework\Frameworks" "Versions\Current\Frameworks"
del "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\WebKit.framework\Versions\Current"
mklink    "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\WebKit.framework\Versions\Current" "A"
del "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\IMCore.framework"
mklink    "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\IMCore.framework" "..\PrivateFrameworks\IMCore.framework"
del "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\JavaVM.framework\Frameworks"
mklink    "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\JavaVM.framework\Frameworks" "Versions\Current\Frameworks"
del "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\JavaVM.framework\Versions\Current"
mklink    "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\JavaVM.framework\Versions\Current" "A"
del "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\System.framework\Versions\Current"
mklink    "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\System.framework\Versions\Current" "B"
del "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\Quartz.framework\Frameworks"
mklink    "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\Quartz.framework\Frameworks" "Versions\Current\Frameworks"
del "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\Quartz.framework\Versions\Current"
mklink    "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\Quartz.framework\Versions\Current" "A"
del "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\AddressBook.framework\Resources"
mklink    "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\AddressBook.framework\Resources" "Versions\Current\Resources"
del "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\AddressBook.framework\Versions\Current"
mklink    "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\AddressBook.framework\Versions\Current" "A"
del "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\Tcl.framework\Resources"
mklink    "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\Tcl.framework\Resources" "Versions\Current\Resources"
del "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\Tcl.framework\Versions\Current"
mklink    "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\Tcl.framework\Versions\Current" "8.5"
del "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\IMServicePlugIn.framework\Frameworks"
mklink    "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\IMServicePlugIn.framework\Frameworks" "Versions\Current\Frameworks"
del "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\IMServicePlugIn.framework\Versions\Current"
mklink    "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\IMServicePlugIn.framework\Versions\Current" "A"
del "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\Python.framework\Versions\Current"
mklink    "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\Python.framework\Versions\Current" "2.7"
del "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\Python.framework\Versions\2.5"
mklink    "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\Python.framework\Versions\2.5" "2.6"
del "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\Python.framework\Versions\2.3"
mklink    "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\Python.framework\Versions\2.3" "2.6"
del "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\Carbon.framework\Frameworks"
mklink /D "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\Carbon.framework\Frameworks" "Versions\Current\Frameworks"
del "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\Carbon.framework\Versions\Current"
mklink /D "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\Carbon.framework\Versions\Current" "A"
del "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\Carbon.framework\Versions\A\Frameworks\Print.framework\Versions\Current"
mklink    "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\Carbon.framework\Versions\A\Frameworks\Print.framework\Versions\Current" "A"
del "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\Kernel.framework\Headers"
mklink /D "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\Kernel.framework\Headers" "Versions\Current\Headers"
del "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\Kernel.framework\Versions\Current"
mklink /D "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\Kernel.framework\Versions\Current" "A"
del "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\Kernel.framework\Versions\A\Headers\AvailabilityMacros.h"
mklink    "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\Kernel.framework\Versions\A\Headers\AvailabilityMacros.h" "..\..\..\..\..\..\..\usr\include\AvailabilityMacros.h"
del "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\Kernel.framework\Versions\A\Headers\Availability.h"
mklink    "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\Kernel.framework\Versions\A\Headers\Availability.h" "..\..\..\..\..\..\..\usr\include\Availability.h"
del "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\Kernel.framework\Versions\A\Headers\AvailabilityInternal.h"
mklink    "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\Kernel.framework\Versions\A\Headers\AvailabilityInternal.h" "..\..\..\..\..\..\..\usr\include\AvailabilityInternal.h"
del "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\Accelerate.framework\Frameworks"
mklink    "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\Accelerate.framework\Frameworks" "Versions\Current\Frameworks"
del "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\Accelerate.framework\Versions\Current"
mklink    "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\Accelerate.framework\Versions\Current" "A"
del "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\AVFoundation.framework\Frameworks"
mklink    "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\AVFoundation.framework\Frameworks" "Versions\Current\Frameworks"
del "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\AVFoundation.framework\Resources"
mklink    "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\AVFoundation.framework\Resources" "Versions\Current\Resources"
del "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\AVFoundation.framework\Versions\Current"
mklink    "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\AVFoundation.framework\Versions\Current" "A"
del "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\CoreServices.framework\Frameworks"
mklink    "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\CoreServices.framework\Frameworks" "Versions\Current\Frameworks"
del "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\CoreServices.framework\Versions\Current"
mklink    "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\CoreServices.framework\Versions\Current" "A"
del "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\QuartzCore.framework\Versions\Current"
mklink /D "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\QuartzCore.framework\Versions\Current" "A"
del "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\QuartzCore.framework\Versions\A\Frameworks\CoreImage.framework"
mklink    "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\QuartzCore.framework\Versions\A\Frameworks\CoreImage.framework" "..\..\..\..\CoreImage.framework"
del "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\ApplicationServices.framework\Frameworks"
mklink /D "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\ApplicationServices.framework\Frameworks" "Versions\A\Frameworks"
del "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\ApplicationServices.framework\Versions\Current"
mklink /D "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\ApplicationServices.framework\Versions\Current" "A"
del "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\ApplicationServices.framework\Versions\A\Frameworks\SpeechSynthesis.framework\Resources"
mklink    "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\ApplicationServices.framework\Versions\A\Frameworks\SpeechSynthesis.framework\Resources" "Versions\Current\Resources"
del "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\ApplicationServices.framework\Versions\A\Frameworks\SpeechSynthesis.framework\Versions\Current"
mklink    "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\ApplicationServices.framework\Versions\A\Frameworks\SpeechSynthesis.framework\Versions\Current" "A"
del "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\ApplicationServices.framework\Versions\A\Frameworks\CoreGraphics.framework"
mklink    "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\ApplicationServices.framework\Versions\A\Frameworks\CoreGraphics.framework" "..\..\..\..\CoreGraphics.framework"
del "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\ApplicationServices.framework\Versions\A\Frameworks\ImageIO.framework"
mklink    "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\ApplicationServices.framework\Versions\A\Frameworks\ImageIO.framework" "..\..\..\..\ImageIO.framework"
del "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\ApplicationServices.framework\Versions\A\Frameworks\CoreText.framework"
mklink    "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\ApplicationServices.framework\Versions\A\Frameworks\CoreText.framework" "..\..\..\..\CoreText.framework"
del "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\Tk.framework\Resources"
mklink    "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\Tk.framework\Resources" "Versions\Current\Resources"
del "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\Tk.framework\Versions\Current"
mklink    "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\Tk.framework\Versions\Current" "8.5"
del "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\vecLib.framework\Versions\Current"
mklink    "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\vecLib.framework\Versions\Current" "A"
del "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\CoreMIDIServer.framework\Versions\Current"
mklink    "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\CoreMIDIServer.framework\Versions\Current" "A"
del "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\OpenDirectory.framework\Frameworks"
mklink    "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\OpenDirectory.framework\Frameworks" "Versions\Current\Frameworks"
del "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\OpenDirectory.framework\Versions\Current"
mklink    "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\OpenDirectory.framework\Versions\Current" "A"
del "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\Ruby.framework\Headers"
mklink /D "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\Ruby.framework\Headers" "Versions\Current\Headers"
del "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\Ruby.framework\Versions\Current"
mklink /D "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\Ruby.framework\Versions\Current" "2.0"
del "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\Ruby.framework\Versions\2.0\Headers\ruby\ruby"
mklink /D "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\System\Library\Frameworks\Ruby.framework\Versions\2.0\Headers\ruby\ruby" "."
del "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\usr\include\sched.h"
mklink    "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\usr\include\sched.h" "pthread\sched.h"
del "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\usr\include\pthread.h"
mklink    "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\usr\include\pthread.h" "pthread\pthread.h"
del "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\usr\include\pthread_impl.h"
mklink    "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\bsd_x86_64\sys_headers\usr\include\pthread_impl.h" "pthread\pthread_impl.h"
del "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\solaris_sparc_64\sys_headers\usr\include\iso\errno_iso.h"
mklink    "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\solaris_sparc_64\sys_headers\usr\include\iso\errno_iso.h" "..\errno.h"
del "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\solaris_sparc_64\sys_headers\usr\include\iso\float_iso.h"
mklink    "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\solaris_sparc_64\sys_headers\usr\include\iso\float_iso.h" "..\float.h"
del "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\solaris_sparc_64\sys_headers\usr\include\gphoto2\gphoto2"
mklink /D "hotspot_sys_headers_and_outputdir_src\hotspot_cdtproj_closed_src_includes\solaris_sparc_64\sys_headers\usr\include\gphoto2\gphoto2" "."
del "hotspot_sys_headers_and_outputdir_src\linux_ppc_64\sys_headers\usr\include\asm"
mklink /D "hotspot_sys_headers_and_outputdir_src\linux_ppc_64\sys_headers\usr\include\asm" "asm-powerpc"
del "hotspot_sys_headers_and_outputdir_src\linux_s390_64\sys_headers\usr\include\asm"
mklink /D "hotspot_sys_headers_and_outputdir_src\linux_s390_64\sys_headers\usr\include\asm" "asm-s390"
del "hotspot_sys_headers_and_outputdir_src\linux_s390_64\sys_headers\usr\include\c++\4.3\s390x-suse-linux\32"
mklink /D "hotspot_sys_headers_and_outputdir_src\linux_s390_64\sys_headers\usr\include\c++\4.3\s390x-suse-linux\32" "."
del "hotspot_sys_headers_and_outputdir_src\bsd_x86_64"
mklink /D "hotspot_sys_headers_and_outputdir_src\bsd_x86_64" "hotspot_cdtproj_closed_src_includes\bsd_x86_64"
del "hotspot_sys_headers_and_outputdir_src\solaris_sparc_64"
mklink /D "hotspot_sys_headers_and_outputdir_src\solaris_sparc_64" "hotspot_cdtproj_closed_src_includes\solaris_sparc_64"
del "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\bits"
mklink /D "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\bits" "x86_64-linux-gnu\bits"
del "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\asm"
mklink /D "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\asm" "x86_64-linux-gnu\asm"
del "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\gnu"
mklink /D "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\gnu" "x86_64-linux-gnu\gnu"
del "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\x86_64-linux-gnu\c++\5.4.0"
mklink /D "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\x86_64-linux-gnu\c++\5.4.0" "5"
del "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\c++\5.4.0"
mklink /D "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\c++\5.4.0" "5"
del "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\cdefs.h"
mklink    "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\cdefs.h" "..\x86_64-linux-gnu\sys\cdefs.h"
del "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\time.h"
mklink    "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\time.h" "..\x86_64-linux-gnu\sys\time.h"
del "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\ioctl.h"
mklink    "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\ioctl.h" "..\x86_64-linux-gnu\sys\ioctl.h"
del "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\stat.h"
mklink    "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\stat.h" "..\x86_64-linux-gnu\sys\stat.h"
del "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\poll.h"
mklink    "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\poll.h" "..\x86_64-linux-gnu\sys\poll.h"
del "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\uio.h"
mklink    "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\uio.h" "..\x86_64-linux-gnu\sys\uio.h"
del "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\utsname.h"
mklink    "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\utsname.h" "..\x86_64-linux-gnu\sys\utsname.h"
del "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\param.h"
mklink    "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\param.h" "..\x86_64-linux-gnu\sys\param.h"
del "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\socket.h"
mklink    "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\socket.h" "..\x86_64-linux-gnu\sys\socket.h"
del "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\sysinfo.h"
mklink    "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\sysinfo.h" "..\x86_64-linux-gnu\sys\sysinfo.h"
del "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\resource.h"
mklink    "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\resource.h" "..\x86_64-linux-gnu\sys\resource.h"
del "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\shm.h"
mklink    "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\shm.h" "..\x86_64-linux-gnu\sys\shm.h"
del "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\ttydefaults.h"
mklink    "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\ttydefaults.h" "..\x86_64-linux-gnu\sys\ttydefaults.h"
del "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\times.h"
mklink    "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\times.h" "..\x86_64-linux-gnu\sys\times.h"
del "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\select.h"
mklink    "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\select.h" "..\x86_64-linux-gnu\sys\select.h"
del "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\syscall.h"
mklink    "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\syscall.h" "..\x86_64-linux-gnu\sys\syscall.h"
del "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\ucontext.h"
mklink    "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\ucontext.h" "..\x86_64-linux-gnu\sys\ucontext.h"
del "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\ipc.h"
mklink    "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\ipc.h" "..\x86_64-linux-gnu\sys\ipc.h"
del "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\types.h"
mklink    "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\types.h" "..\x86_64-linux-gnu\sys\types.h"
del "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\wait.h"
mklink    "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\wait.h" "..\x86_64-linux-gnu\sys\wait.h"
del "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\mman.h"
mklink    "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\mman.h" "..\x86_64-linux-gnu\sys\mman.h"
del "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\sysmacros.h"
mklink    "hotspot_sys_headers_and_outputdir_src\linux_x86_64\sys_headers\usr\include\sys\sysmacros.h" "..\x86_64-linux-gnu\sys\sysmacros.h"
pause
